"""Verify the 3-bit storage claim of `nvfp4lloyd43upcast` on a REAL checkpoint.

    python cluster_scripts/verify_upcast.py <step_dir>          # one exported step
    python cluster_scripts/verify_upcast.py <step_dir> --tol 0  # require bit-equality

WHY
---
The format's premise is that the packed NVFP4 prefill checkpoint is a pure function of
the 3-bit Lloyd43 decode weight -- so only the decode half has to be STORED, and prefill
can be regenerated by upcasting LUT3 -> NVFP4. The unit tests prove that on a 2-layer toy
model; this proves it on a full export, which is where shape and fused-group scale bugs
actually show up.

It reconstructs `weight_packed` and `weight_scale` from the exported bf16 decode weight
alone and requires them to match the shipped prefill tensors EXACTLY. The global scale is
read back out of the prefill file (stored reciprocal), because it is a fused-group
quantity -- gate/up and q/k/v share one, and recomputing it per-layer would disagree.

A mismatch means the shipped prefill weight is NOT derivable from the 3-bit one, i.e. the
storage claim is false for that checkpoint -- most likely because training and export
disagree about which tensor prefill quantizes.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import torch
from safetensors.torch import load_file

from quantizers.nvfp4 import pack_nvfp4_weight


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("step_dir", help="an exported step dir containing prefill/ and decode/")
    ap.add_argument("--block", type=int, default=16)
    args = ap.parse_args()

    P = load_file(os.path.join(args.step_dir, "prefill", "model.safetensors"))
    D = load_file(os.path.join(args.step_dir, "decode", "model.safetensors"))
    bases = sorted({k[: -len(".weight_packed")] for k in P if k.endswith("weight_packed")})
    if not bases:
        raise SystemExit("no packed prefill tensors found -- is this an upcast checkpoint?")

    bad_p, bad_s, missing = [], [], []
    for b in bases:
        if b + ".weight" not in D:
            missing.append(b)
            continue
        dec = D[b + ".weight"].cuda().float()          # the 3-bit weight, dequantized
        gs = (1.0 / P[b + ".weight_global_scale"].cuda().float()).reshape(())
        p2, s2, _ = pack_nvfp4_weight(dec, args.block, global_scale=gs, signed=False)
        if not torch.equal(p2.cpu(), P[b + ".weight_packed"]):
            bad_p.append(b)
        if not torch.equal(s2.cpu().float(), P[b + ".weight_scale"].float()):
            bad_s.append(b)

    print(f"  layers checked            : {len(bases)}")
    print(f"  decode half missing       : {len(missing)}")
    print(f"  packed codes mismatching  : {len(bad_p)}")
    print(f"  block scales mismatching  : {len(bad_s)}")
    for b in (bad_p + bad_s)[:5]:
        print(f"      e.g. {b}")
    ok = not (bad_p or bad_s or missing)
    print("  VERDICT:", "prefill is EXACTLY derivable from the 3-bit decode weight"
          if ok else "NOT derivable -- the 3-bit storage claim is FALSE here")
    raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
