"""Reasoning SFT data: faunix/Qwen3.8-27B-Distillation-40K.

WHY THIS ONE. QAD distils to the TEACHER's distribution -- the loss is KL against the
frozen bf16 teacher, and the labels only choose which POSITIONS are scored. So a
reasoning corpus is useful here to the extent that it puts the model into states the
teacher actually produces. These traces were generated by Qwen3.8-27B itself, which is
exactly the teacher, and they already carry a real <think> block in the teacher's own
format. A corpus traced by some other model (OpenMathReasoning is DeepSeek-R1/QwQ) would
supply reasoning-shaped context that the teacher never generates.

WHAT IT REPLACES. Tulu has no reasoning traces, and the Qwen3.5 template injects
`<think>\\n\\n</think>` into every assistant turn regardless -- so the current setup
supervises the model to emit an EMPTY think block and answer immediately, on every one of
200M tokens, while the template's own system prompt says "Reasoning effort is set to
xhigh". This corpus removes that contradiction.

MEASURED (39998 rows after filtering, tokenized through the REAL training path,
training/data._tokenize_with_labels, with the Qwen3.5 chat template):
    total sequence          median 3172  mean 5806  p90 12185  p99 46402  max 102624
    supervised (DECODE)     median 2900
    unsupervised (PREFILL)  median  111
    think (dataset column)  median  797  mean 2551
    fits in 2048: 38.9%   4096: 56.4%   8192: 81.8%   16384: 93.3%

So the median example does not come close to fitting the old max_seq_len of 2048, and
almost the whole sequence is supervised -- the prompt is ~111 tokens and the rest is the
model's own reasoning + answer.
"""
import json

from datasets import load_dataset

DATASET = "faunix/Qwen3.8-27B-Distillation-40K"

# Markers of machinery this setup cannot express. An executed tool round-trip is not a
# <think> block and there is no tool runtime here, so those rows would train the model to
# emit a call that never gets answered. Fenced code INSIDE a trace is NOT filtered: that
# is just text the model wrote, and `code` is the largest domain in the corpus (16006 of
# 40000). Only 2 rows are dropped for tool use.
TOOL_MARKERS = ("<tool_call>", "</tool_call>", "<tool_response>", "</tool_response>",
                "<|tool_call|>", "function_call")


def _usable(row) -> bool:
    blob = json.dumps(row["messages"])
    if any(m in blob for m in TOOL_MARKERS):
        return False
    roles = {m.get("role") for m in row["messages"]}
    if roles - {"system", "user", "assistant"}:
        return False
    # _tokenize_with_labels handles multi-turn, but these are single-turn by
    # construction; anything else is a surprise worth dropping rather than guessing at.
    if sum(m.get("role") == "assistant" for m in row["messages"]) != 1:
        return False
    # A row with no think block would reintroduce exactly the empty-reasoning
    # supervision this corpus exists to remove.
    return "<think>" in blob and "</think>" in blob


def _split_think(row):
    """Move the trace out of the assistant's content and into `reasoning_content`.

    The corpus stores the whole reply as one string, `<think>...</think>answer`. The
    Qwen3.5 template does NOT strip that: it emits its own think block and then the
    content verbatim, so a raw row renders as

        <think>\\n\\n</think>\\n\\n<think>\\nLet me analyze...\\n</think>\\n\\nanswer

    -- an EMPTY think block followed by a second one inside the answer body, which is
    exactly the failure mode this corpus is meant to remove. The template has a slot for
    this (`'<think>\\n' + reasoning_content + '\\n</think>\\n\\n' + content`), so the split
    makes it render as one well-formed block. It also puts the label boundary in the right
    place: add_generation_prompt=True ends at `<think>\\n`, so supervision starts at the
    first REASONING token rather than at a `</think>` that closes nothing.

    `reasoning_content` is set on every message, not just the assistant one: `messages` is
    an Arrow list-of-struct and every element must carry the same fields.
    """
    out = []
    for m in row["messages"]:
        content, reasoning = m["content"], ""
        if m.get("role") == "assistant":
            start = content.find("<think>")
            end = content.find("</think>")
            if 0 <= start < end:
                reasoning = content[start + len("<think>"):end].strip()
                content = content[end + len("</think>"):].lstrip()
        out.append({"role": m["role"], "content": content, "reasoning_content": reasoning})
    return {"messages": out}


def get_reasoning_train_val():
    """(train, val) with tool-use rows removed.

    Length filtering is NOT done here. The `tokens_total` column undercounts what the
    Qwen3.5 chat template actually produces by ~1.4x (median 2322 by the column vs 3172
    through training/data._tokenize_with_labels), so a cap applied to the column would let
    genuinely over-long rows through to be silently truncated. build_chunks drops them
    instead, on the real tokenization -- see its `drop_overlong`.
    """
    ds = load_dataset(DATASET, split="train").filter(_usable).map(_split_think)
    # A row whose answer was empty after the split is all reasoning and no conclusion.
    ds = ds.filter(lambda r: any(m["role"] == "assistant" and m["content"].strip()
                                 and m["reasoning_content"].strip() for m in r["messages"]))
    splits = ds.train_test_split(test_size=0.02, seed=42)
    return splits["train"], splits["test"]
