"""Print, check, or save generated tabular files under notebooks/tables."""
import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path
from common import ROOT

HERE = Path(__file__).resolve().parent
GENERATORS = {
    "minimal_comparison": ["make_main_table.py"],
    "bigmodels": ["make_large_model_table.py", "--quiet"],
    "qadd27b_accuracy": ["make_qadd27b_table.py"],
    "qadd27b_lengths": ["make_qadd27b_lengths_table.py"],
    "interop": ["make_interop_table.py"],
    "prefill-per-model": ["make_prefill_table.py"],
    "nvfp4-breakdown": ["make_breakdown_table.py"],
    **{name: ["make_recorded_table.py", name] for name in ("hyper", "parallel", "models", "attn-backend")},
}


def normalized(text):
    text = re.sub(r"(?<!\\)%[^\n]*", "", text)
    return re.sub(r"\s+", "", text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tables", nargs="+", choices=["all", *GENERATORS])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="fail on differences; never edit")
    mode.add_argument("--write", action="store_true", help="save the selected tables as .tex files")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "notebooks/tables")
    args = parser.parse_args()
    names = list(GENERATORS) if "all" in args.tables else list(dict.fromkeys(args.tables))
    # Generate everything before writing: a missing input never leaves a partial update.
    results = {}
    for name in names:
        script, *options = GENERATORS[name]
        process = subprocess.run([sys.executable, str(HERE / script), *options],
                                 text=True, capture_output=True, cwd=ROOT)
        if process.stderr:
            print(process.stderr, file=sys.stderr, end="")
        if process.returncode:
            raise SystemExit(f"{name}: generator failed ({process.returncode})\n{process.stdout}")
        output = process.stdout.strip()
        if not output.startswith(r"\begin{tabular}") or not output.endswith(r"\end{tabular}"):
            raise SystemExit(f"{name}: generator did not emit a clean tabular")
        results[name] = output
    if not (args.check or args.write):
        for name, output in results.items():
            print(f"% tab:{name}\n{output}")
        return
    different = []
    for name, output in results.items():
        path = args.output_dir / f"{name}.tex"
        existing = path.read_text() if path.exists() else ""
        if normalized(existing) == normalized(output):
            print(f"{name}: matches", file=sys.stderr)
            continue
        different.append(name)
        if args.check:
            print("".join(difflib.unified_diff(existing.splitlines(True), (output + "\n").splitlines(True),
                                               fromfile=str(path), tofile=f"generated/{name}")))
    if args.check and different:
        raise SystemExit("Out of date: " + ", ".join(different))
    if args.write and different:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        for name in different:
            content = f"% Generated by notebooks/table_generators/generate.py {name} --write\n{results[name]}\n"
            (args.output_dir / f"{name}.tex").write_text(content)
        print("Saved: " + ", ".join(different), file=sys.stderr)


if __name__ == "__main__":
    main()
